- name: Install and deploy
  
  hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      tags:
        - install
    - role: geerlingguy.pip
      tags:
        - install

  tasks:
    - name: Start Redmine in container
      community.docker.docker_container:
        image: redmine:latest
        name: redmine
        platform: linux/amd64
        state: started
        restart: true
        ports:
          - "80:3000"
      tags:
        - deploy