- name: Install and deploy
  
  hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      tags:
        - install
    - role: geerlingguy.pip
      tags:
        - install

  tasks:
    - name: Start Redmine in container
      community.docker.docker_container:
        image: redmine:latest
        name: redmine
        platform: linux/amd64
        state: started
        restart: true
        ports:
          - "80:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_PORT: "{{ redmine_db_port }}"
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"
      tags:
        - deploy