---
- name: Install and deploy Redmine
  hosts: all
  become: true
  vars_files:
    - group_vars/webservers/vault.yml  # Используем зашифрованные переменные

  roles:
    - role: geerlingguy.docker
      tags:
        - install
    - role: geerlingguy.pip
      tags:
        - install

  tasks:
    - name: Start Redmine in container
      community.docker.docker_container:
        image: redmine:latest
        name: redmine
        state: started
        restart_policy: always
        ports:
          - "80:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ REDMINE_DB_POSTGRES }}"
          REDMINE_DB_USERNAME: "{{ REDMINE_DB_USERNAME }}"
          REDMINE_DB_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"
          REDMINE_DB_PORT: "{{ REDMINE_DB_PORT }}"
          REDMINE_DB_DATABASE: "{{ REDMINE_DB_DATABASE }}"
      tags:
        - deploy